import AppKit
import Foundation

/// 시스템 클립보드를 감시해서 새로 복사된 내용을 히스토리에 넣는 역할을 맡습니다.
///
/// macOS에는 "클립보드가 바뀌었다"고 알려주는 공개 알림이 존재하지 않습니다.
/// 그래서 `NSPasteboard`가 제공하는 `changeCount`를 짧은 주기로 확인해서,
/// 이 숫자가 올라갔으면 새로 복사된 것으로 판단하는 방식이 표준적인 해법입니다.
@MainActor
final class ClipboardMonitor {

    /// 클립보드를 확인하는 주기입니다. 사람이 체감하지 못할 만큼 짧으면서도 부담이 적은 값입니다.
    static let pollInterval: TimeInterval = 0.4

    /// 비밀번호 관리자를 비롯한 민감한 도구가 붙여두는 표식입니다.
    /// 이 중 하나라도 붙어 있으면 해당 복사 내용은 아예 읽지 않고 건너뜁니다.
    private static let privacyTypeNames: Set<String> = [
        "org.nspasteboard.transienttype",
        "org.nspasteboard.concealedtype",
        "org.nspasteboard.autogeneratedtype",
    ]

    private let pasteboard = NSPasteboard.general
    private let store: HistoryStore
    private var lastChangeCount: Int
    private var timer: Timer?

    init(store: HistoryStore) {
        self.store = store
        // 앱을 켜는 순간 이미 클립보드에 있던 내용까지 끌어오지는 않도록 현재 값에서 출발합니다.
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let timer = Timer.scheduledTimer(withTimeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.checkForChanges()
            }
        }
        // 메뉴를 열어둔 동안에도 감시가 멈추지 않도록 공용 실행 루프 모드에 등록합니다.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// 앱이 스스로 클립보드에 쓴 내용을 다시 감지하지 않도록, 방금 만든 변경을 기록해 둡니다.
    func acknowledgeSelfWrite(changeCount: Int) {
        lastChangeCount = changeCount
    }

    // MARK: - 감지

    private func checkForChanges() {
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        guard !containsPrivacyMarker() else { return }

        for capture in readCaptures() {
            store.insert(capture)
        }
    }

    /// 민감한 내용임을 알리는 표식이 붙어 있는지 확인합니다. 대소문자는 구분하지 않습니다.
    private func containsPrivacyMarker() -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { Self.privacyTypeNames.contains($0.rawValue.lowercased()) }
    }

    /// 지금 클립보드에 담긴 내용을 종류에 맞게 읽어냅니다.
    ///
    /// 파일을 여러 개 한꺼번에 복사한 경우에는 파일마다 항목을 하나씩 만듭니다.
    private func readCaptures() -> [ClipboardCapture] {
        // 파일이 가장 구체적인 형태이므로 먼저 확인합니다.
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            return urls.map { .file($0) }
        }

        // 파일이 아니라면 이미지인지 확인합니다.
        if let capture = readImageCapture() {
            return [capture]
        }

        // 마지막으로 문자열을 확인합니다. 빈 문자열이나 공백뿐인 내용은 저장하지 않습니다.
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return [.text(string)]
        }

        return []
    }

    /// 클립보드의 이미지를 PNG 데이터로 통일해서 가져옵니다.
    ///
    /// 스크린샷처럼 아직 디스크에 파일로 존재하지 않는 이미지는 TIFF 형태로 올라오는 경우가 많은데,
    /// 이를 PNG로 변환해 두면 저장과 드래그를 모두 같은 방식으로 처리할 수 있습니다.
    private func readImageCapture() -> ClipboardCapture? {
        if let pngData = pasteboard.data(forType: .png) {
            return .image(data: pngData, fileExtension: "png")
        }

        if let tiffData = pasteboard.data(forType: .tiff),
           let bitmap = NSBitmapImageRep(data: tiffData),
           let pngData = bitmap.representation(using: .png, properties: [:]) {
            return .image(data: pngData, fileExtension: "png")
        }

        return nil
    }
}
